services:
  droneautocuts:
    build: .
    container_name: droneautocuts
    gpus: all
    environment:
      - USE_GPU=1
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./normalized:/app/normalized